# Generated by Django 2.0.6 on 2018-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyContacct', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='MyContact',
        ),
    ]
