# Generated by Django 2.0.6 on 2018-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyContacct', '0003_auto_20180616_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('userName', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('contactAdress', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MYContact1',
        ),
    ]
