# Generated by Django 2.0.6 on 2018-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyContacct', '0005_auto_20180617_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontact',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
